### ISSUE TITLE
Error while running application1.py

### ISSUE THREAD

**Issue by jishnujayakumar** [rbccps-iisc/GT-Buddy#1]
Traceback (most recent call last):
  File "application1.py", line 19, in <module>
    from ImageBlock import ImageWindow
  File "/home/jishnu/Documents/github/GT-Buddy/ImageBlock.py", line 1, in <module>
    from PyQt5.QtWidgets import QLabel
ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

**Comment by jishnujayakumar** [comment]
Strictly use python3.6 while running application1.py
